version: '3.8'

services:
  web:
    build: .
    user: root
    command: gunicorn animals.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - animals_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/testing/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - animals_net
    depends_on:
      web:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    expose:
      - "6379"
    networks:
      - animals_net

  celery_worker:
    build: .
    command: celery -A animals worker -l info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - animals_net

  celery_beat:
    build: .
    command: celery -A animals beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - animals_net

networks:
  animals_net:
    driver: bridge

volumes:
  static_volume:
  media_volume: