# Generated by Django 5.2.1 on 2025-05-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Главное изображение для статьи, отображаемое в превью и на странице статьи.",
                null=True,
                upload_to="article_images/%Y/%m/%d/",
                verbose_name="главное изображение",
            ),
        ),
    ]
