# Generated by Django 5.2.1 on 2025-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0002_article_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название категории"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Используется в URL. Оставьте пустым для автоматической генерации (на латинице).",
                        max_length=100,
                        unique=True,
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория статей",
                "verbose_name_plural": "категории статей",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="siteapp.articlecategory",
                verbose_name="категории",
            ),
        ),
    ]
