# Generated by Django 5.2.1 on 2025-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0003_articlecategory_article_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар пользователя",
                null=True,
                upload_to="user_avatars/",
                verbose_name="аватар",
            ),
        ),
    ]
