# Generated by Django 5.2.1 on 2025-05-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0004_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название окраса"
                    ),
                ),
            ],
            options={
                "verbose_name": "окрас животного",
                "verbose_name_plural": "окрасы животных",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnimalGender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="пол"),
                ),
            ],
            options={
                "verbose_name": "пол животного",
                "verbose_name_plural": "пол животных",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="siteapp.animalcolor",
                verbose_name="окрас",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="siteapp.animalgender",
                verbose_name="пол",
            ),
        ),
    ]
