# Generated by Django 5.2.1 on 2025-05-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0005_animalcolor_animalgender_animal_color_animal_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="номер телефона"
            ),
        ),
    ]
