# Generated by Django 5.2.1 on 2025-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0006_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_create_article",
            field=models.BooleanField(
                default=False, verbose_name="может создавать статьи"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_any_article",
            field=models.BooleanField(
                default=False, verbose_name="может удалять любые статьи"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_own_article",
            field=models.BooleanField(
                default=False, verbose_name="может удалять свои статьи"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_any_article",
            field=models.BooleanField(
                default=False, verbose_name="может редактировать любые статьи"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_own_article",
            field=models.BooleanField(
                default=False, verbose_name="может редактировать свои статьи"
            ),
        ),
    ]
