# Generated by Django 5.2.1 on 2025-05-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "siteapp",
            "0007_role_can_create_article_role_can_delete_any_article_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_delete_any_comment",
            field=models.BooleanField(
                default=False,
                verbose_name="может удалять любые комментарии (модерация)",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_own_comment",
            field=models.BooleanField(
                default=True, verbose_name="может удалять свои комментарии"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_own_comment",
            field=models.BooleanField(
                default=True, verbose_name="может редактировать свои комментарии"
            ),
        ),
    ]
