# Generated by Django 5.2.1 on 2025-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0008_role_can_delete_any_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_create_advertisement",
            field=models.BooleanField(
                default=True, verbose_name="может создавать объявления"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_delete_own_advertisement",
            field=models.BooleanField(
                default=True, verbose_name="может удалять свои объявления"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_edit_own_advertisement",
            field=models.BooleanField(
                default=True, verbose_name="может редактировать свои объявления"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="can_manage_any_advertisement",
            field=models.BooleanField(
                default=False,
                verbose_name="может управлять любыми объявлениями (модерация)",
            ),
        ),
    ]
