# Generated by Django 5.2.1 on 2025-05-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0009_role_can_create_advertisement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мальчик"), ("F", "Девочка"), ("U", "Не указан")],
                max_length=1,
                null=True,
                verbose_name="пол",
            ),
        ),
        migrations.DeleteModel(
            name="AnimalGender",
        ),
    ]
