# Generated by Django 5.2.1 on 2025-05-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0011_alter_animal_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мальчик"), ("F", "Девочка"), ("U", "Не указан")],
                default="U",
                max_length=1,
                verbose_name="пол",
            ),
        ),
    ]
