# Generated by Django 5.2.1 on 2025-05-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0012_alter_animal_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="website",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="веб-сайт приюта"
            ),
        ),
    ]
