# Generated by Django 5.2.1 on 2025-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0013_shelter_website"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalinshelter",
            options={
                "ordering": ["shelter", "animal", "-date_admitted"],
                "verbose_name": "животное в приюте",
                "verbose_name_plural": "животные в приютах",
            },
        ),
        migrations.AddField(
            model_name="animal",
            name="shelters",
            field=models.ManyToManyField(
                related_name="animals_in_shelter",
                through="siteapp.AnimalInShelter",
                to="siteapp.shelter",
                verbose_name="приюты, в которых состоит",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="animals",
            field=models.ManyToManyField(
                blank=True,
                through="siteapp.AnimalInShelter",
                to="siteapp.animal",
                verbose_name="животные в приюте",
            ),
        ),
    ]
