# Generated by Django 5.2.1 on 2025-06-14 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0014_alter_animalinshelter_options_animal_shelters_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть введен в формате: '+999999999'. До 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
        migrations.CreateModel(
            name="AdvertisementRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="оценка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="дата оценки"),
                ),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="siteapp.advertisement",
                        verbose_name="объявление",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_ratings_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка объявления",
                "verbose_name_plural": "оценки объявлений",
                "ordering": ["-created_at"],
                "unique_together": {("advertisement", "user")},
            },
        ),
    ]
