# Generated by Django 5.2.1 on 2025-06-16 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteapp", "0015_alter_user_phone_number_advertisementrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresponse",
            name="message",
            field=models.TextField(help_text="Текст отклика", verbose_name="сообщение"),
        ),
        migrations.AlterField(
            model_name="advertisementrating",
            name="advertisement",
            field=models.ForeignKey(
                help_text="Объявление, которое было оценено.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="siteapp.advertisement",
                verbose_name="объявление",
            ),
        ),
        migrations.AlterField(
            model_name="advertisementrating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата, когда была оставлена оценка.",
                verbose_name="дата оценки",
            ),
        ),
        migrations.AlterField(
            model_name="advertisementrating",
            name="rating",
            field=models.PositiveSmallIntegerField(
                help_text="Оценка, которую пользователь оставил.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="оценка",
            ),
        ),
        migrations.AlterField(
            model_name="advertisementrating",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, который оставил оценку.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_ratings_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="animalinshelter",
            name="date_admitted",
            field=models.DateField(
                auto_now_add=True,
                help_text="Дата, когда животное поступило в приют",
                null=True,
                verbose_name="дата поступления",
            ),
        ),
    ]
